language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -e CI=true -t ksneha24/docker-react -f Dockerfile.dev .

script:
  - docker run ksneha24/docker-react npm run test -- --coverage

